### ISSUE TITLE
Tables do not support time-dimension columns

### ISSUE THREAD

**Issue by cythrawll** [yahoo/yavin#879]
**Describe the bug**
Now that we load time-dimensions in it's own metadata bucket. adding time-dimensions to table columns breaks tables.

**Expected behavior**
Tables with time-dimensions render.

**Additional context**
Tables store column type in it's model as 'dimension'.  Need it to support column type of 'time-dimension' in it's model, this should fix metadata lookups.

**Comment by kevinhinterlong** [comment]
Removed in https://github.com/yahoo/yavin/pull/1081
